name: El blog del Kohai
description: 

url: http://rpuscas.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
